# TODO: merge with build.yml
# Workflow file by Eknous
# Damnit GitHub...
name: Build furnace (Android)

on:
  push:
    branches: 
      - master
      - ay-timer
  pull_request:
    branches:
      - master
      - ay-timer

defaults:
  run:
    shell: bash

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        submodules: recursive

    - name: Set package identifier
      id: package-identify
      run: |
        package_name="furnace-${GITHUB_SHA}"
        package_ext=""

        package_name="${package_name}-Android"
        package_ext=".tar.gz"

        echo "Package identifier: ${package_name}"
        echo "Package file: ${package_name}${package_ext}"

        echo "id=${package_name}" >> $GITHUB_OUTPUT
        echo "filename=${package_name}${package_ext}" >> $GITHUB_OUTPUT

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install \
          libsdl2-dev \
          libfmt-dev \
          librtmidi-dev \
          libsndfile1-dev \
          zlib1g-dev \
          libjack-jackd2-dev

    - name: Build (run Gradle)
      id: build
      run: |
        cd ${PWD}/android/
        ./gradlew assembleRelease
        ./gradlew --stop
        cd ../..
        echo "machete=${PWD}" >> $GITHUB_OUTPUT

    # do i really trust the Github Marketplace?
    - name: Sign the APK
      uses: ilharp/sign-android-release@v1
      # ID used to access action output
      id: sign_app
      with:
        releaseDir: android/app/build/outputs/apk/release/
        signingKey: ${{ secrets.SIGNINGKEYBASE64 }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}

    - name: Package
      run: |

        mkdir -p target/furnace
        # if this fails i'm going to present top gear

        mv ${{ steps.sign_app.outputs.signedFile }} target/furnace/${{ steps.package-identify.outputs.id }}.apk
        pushd target/furnace

        cp ../../LICENSE .
        cp ../../res/releaseReadme/unstable-other.txt .
        cp -r ../../papers papers

        popd

        cd target
        tar -zcv -f ../${{ steps.package-identify.outputs.filename }} furnace

    - name: Upload artifact
      #if: ${{ github.repository == 'Eknous-P/furnace' && github.ref_name == 'android-actions-test' }}
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ${{ steps.package-identify.outputs.id }}
        path: ${{ steps.package-identify.outputs.filename }}ï¿¼Enter
